### ISSUE TITLE
[bugreport] Auto bugreport for route undefined

### ISSUE THREAD

**Issue by rdfbot** [almasen/rdf-mapped#100]
### Route undefined

TESTING RDFBOT-5

Metadata:
```yaml
{
    "report": "TESTING RDFBOT-5",
    "originalURL": "rdfbot-testing-bugrep-5"
}
```
