### ISSUE TITLE
[bugreport] Auto bugreport for route undefined

### ISSUE THREAD

**Issue by rdfbot** [almasen/rdf-mapped#102]
### Route undefined

TESTING RDFBOT-6

Metadata:
```yaml
{
    "report": "TESTING RDFBOT-6",
    "originalURL": "rdfbot-testing-bugrep-6"
}
```
