### ISSUE TITLE
[feature request] rdfbot-testing-fr-6

### ISSUE THREAD

**Issue by rdfbot** [almasen/rdf-mapped#103]
### rdfbot-testing-fr-6

Why can't this site brew my tea?-6

Metadata:
```yaml
{
    "message": "Why can't this site brew my tea?-6",
    "subject": "rdfbot-testing-fr-6"
}
```
