### ISSUE TITLE
[bugreport] Auto bugreport for route undefined

### ISSUE THREAD

**Issue by rdfbot** [almasen/rdf-mapped#104]
### Route undefined

TESTING RDFBOT-7

Metadata:
```yaml
{
    "report": "TESTING RDFBOT-7",
    "originalURL": "rdfbot-testing-bugrep-7"
}
```
