### ISSUE TITLE
[feature request] rdfbot-testing-fr-7

### ISSUE THREAD

**Issue by rdfbot** [almasen/rdf-mapped#105]
### rdfbot-testing-fr-7

Why can't this site brew my tea?-7

Metadata:
```yaml
{
    "message": "Why can't this site brew my tea?-7",
    "subject": "rdfbot-testing-fr-7"
}
```
