### ISSUE TITLE
[bugreport] Auto bugreport for route undefined

### ISSUE THREAD

**Issue by rdfbot** [almasen/rdf-mapped#106]
### Route undefined

TESTING RDFBOT-8

Metadata:
```yaml
{
    "report": "TESTING RDFBOT-8",
    "originalURL": "rdfbot-testing-bugrep-8"
}
```
