### ISSUE TITLE
[feature request] rdfbot-testing-fr-8

### ISSUE THREAD

**Issue by rdfbot** [almasen/rdf-mapped#107]
### rdfbot-testing-fr-8

Why can't this site brew my tea?-8

Metadata:
```yaml
{
    "message": "Why can't this site brew my tea?-8",
    "subject": "rdfbot-testing-fr-8"
}
```
