### ISSUE TITLE
[bugreport] Auto bugreport for route undefined

### ISSUE THREAD

**Issue by rdfbot** [almasen/rdf-mapped#108]
### Route undefined

TESTING RDFBOT-9

Metadata:
```yaml
{
    "report": "TESTING RDFBOT-9",
    "originalURL": "rdfbot-testing-bugrep-9"
}
```
