### ISSUE TITLE
[feature request] rdfbot-testing-fr-9

### ISSUE THREAD

**Issue by rdfbot** [almasen/rdf-mapped#109]
### rdfbot-testing-fr-9

Why can't this site brew my tea?-9

Metadata:
```yaml
{
    "message": "Why can't this site brew my tea?-9",
    "subject": "rdfbot-testing-fr-9"
}
```
