### ISSUE TITLE
[bugreport] Auto bugreport for route undefined

### ISSUE THREAD

**Issue by rdfbot** [almasen/rdf-mapped#110]
### Route undefined

TESTING RDFBOT-10

Metadata:
```yaml
{
    "report": "TESTING RDFBOT-10",
    "originalURL": "rdfbot-testing-bugrep-10"
}
```
