### ISSUE TITLE
[feature request] rdfbot-testing-fr-10

### ISSUE THREAD

**Issue by rdfbot** [almasen/rdf-mapped#111]
### rdfbot-testing-fr-10

Why can't this site brew my tea?-10

Metadata:
```yaml
{
    "message": "Why can't this site brew my tea?-10",
    "subject": "rdfbot-testing-fr-10"
}
```
