### ISSUE TITLE
[bugreport] Auto bugreport for route undefined

### ISSUE THREAD

**Issue by rdfbot** [almasen/rdf-mapped#112]
### Route undefined

TESTING RDFBOT-11

Metadata:
```yaml
{
    "report": "TESTING RDFBOT-11",
    "originalURL": "rdfbot-testing-bugrep-11"
}
```
