### ISSUE TITLE
[feature request] rdfbot-testing-fr-11

### ISSUE THREAD

**Issue by rdfbot** [almasen/rdf-mapped#113]
### rdfbot-testing-fr-11

Why can't this site brew my tea?-11

Metadata:
```yaml
{
    "message": "Why can't this site brew my tea?-11",
    "subject": "rdfbot-testing-fr-11"
}
```
