### ISSUE TITLE
[bugreport] Auto bugreport for route rdfbot-testing-bugrep-0

### ISSUE THREAD

**Issue by rdfbot** [almasen/rdf-mapped#117]
### Route rdfbot-testing-bugrep-0

TESTING RDFBOT-0

Metadata:
```yaml
{
    "report": "TESTING RDFBOT-0",
    "originalUrl": "rdfbot-testing-bugrep-0"
}
```
