### ISSUE TITLE
[bugreport] Auto bugreport for route rdfbot-testing-bugrep-1

### ISSUE THREAD

**Issue by rdfbot** [almasen/rdf-mapped#119]
### Route rdfbot-testing-bugrep-1

TESTING RDFBOT-1

Metadata:
```yaml
{
    "report": "TESTING RDFBOT-1",
    "originalUrl": "rdfbot-testing-bugrep-1"
}
```
