### ISSUE TITLE
[bugreport] Auto bugreport for route rdfbot-testing-bugrep-2

### ISSUE THREAD

**Issue by rdfbot** [almasen/rdf-mapped#121]
### Route rdfbot-testing-bugrep-2

TESTING RDFBOT-2

Metadata:
```yaml
{
    "report": "TESTING RDFBOT-2",
    "originalUrl": "rdfbot-testing-bugrep-2"
}
```
