### ISSUE TITLE
[bugreport] Auto bugreport for route rdfbot-testing-bugrep-3

### ISSUE THREAD

**Issue by rdfbot** [almasen/rdf-mapped#123]
### Route rdfbot-testing-bugrep-3

TESTING RDFBOT-3

Metadata:
```yaml
{
    "report": "TESTING RDFBOT-3",
    "originalUrl": "rdfbot-testing-bugrep-3"
}
```
