### ISSUE TITLE
[bugreport] Auto bugreport for route rdfbot-testing-bugrep-4

### ISSUE THREAD

**Issue by rdfbot** [almasen/rdf-mapped#125]
### Route rdfbot-testing-bugrep-4

TESTING RDFBOT-4

Metadata:
```yaml
{
    "report": "TESTING RDFBOT-4",
    "originalUrl": "rdfbot-testing-bugrep-4"
}
```
