### ISSUE TITLE
[bugreport] Auto bugreport for route rdfbot-testing-bugrep-5

### ISSUE THREAD

**Issue by rdfbot** [almasen/rdf-mapped#127]
### Route rdfbot-testing-bugrep-5

TESTING RDFBOT-5

Metadata:
```yaml
{
    "report": "TESTING RDFBOT-5",
    "originalUrl": "rdfbot-testing-bugrep-5"
}
```
