### ISSUE TITLE
[feature request] rdfbot-testing-fr-5

### ISSUE THREAD

**Issue by rdfbot** [almasen/rdf-mapped#128]
### rdfbot-testing-fr-5

Why can't this site brew my tea?-5

Metadata:
```yaml
{
    "message": "Why can't this site brew my tea?-5",
    "subject": "rdfbot-testing-fr-5"
}
```
