### ISSUE TITLE
[bugreport] Auto bugreport for route /course/132

### ISSUE THREAD

**Issue by rdfbot** [almasen/rdf-mapped#129]
### Route /course/132

TESTING RDFBOT: 5.1

Metadata:
```yaml
{
    "timestamp": "Mon, 21 Sep 2020 15:19:04 GMT",
    "originalUrl": "/course/132",
    "ip": "22851f0dcf60d40b141761a8a647ddab099b02cf557aa2b12926f757a06b1dfa",
    "email": "",
    "report": "TESTING RDFBOT: 5.1"
}
```
