### ISSUE TITLE
[feature request] TESTING RDFBOT: 5.2

### ISSUE THREAD

**Issue by rdfbot** [almasen/rdf-mapped#130]
### TESTING RDFBOT: 5.2

TESTING RDFBOT: 5.2

Metadata:
```yaml
{
    "_csrf": "GlKoQ1Ov-PDpZsxfiIbb7tOjUPhERpRnfgSY",
    "reason": "feature_request",
    "name": "ce0c8e0fb7489246f842622a5608e4985566418981ea4ff7c164ca14afd0904d",
    "subject": "TESTING RDFBOT: 5.2",
    "email": "73903ec7ec6bc365ea2e8f2c5e1723935f551c4d1567cbf60bd3ce24e60b98bb",
    "message": "TESTING RDFBOT: 5.2",
    "g-recaptcha-response": "54cb111fd0c9507ba198720bd285e0d3a829e1d85e046940aa8ba97671f7769e",
    "timestamp": "Mon, 21 Sep 2020 15:20:13 GMT",
    "ip": "22851f0dcf60d40b141761a8a647ddab099b02cf557aa2b12926f757a06b1dfa"
}
```
