### ISSUE TITLE
[feature request] When will this site be advertised to supervisors?

### ISSUE THREAD

**Issue by rdfbot** [almasen/rdf-mapped#134]
### When will this site be advertised to supervisors?

When will this site be advertised to supervisors from other colleges/universities?
Thank you

Metadata:
```yaml
{
    "_csrf": "98a4c2a09ca42424a31ab422682e4e6c4ed36a68a8344153b8acb3619fa909c0",
    "reason": "feature_request",
    "name": "8a4a62835cf32c86a73ace5a7b16f6cc581438c37c3e49fd7b21337542c46d69",
    "subject": "When will this site be advertised to supervisors?",
    "email": "87924606b4131a8aceeeae8868531fbb9712aaa07a5d3a756b26ce0f5d6ca674",
    "message": "When will this site be advertised to supervisors from other colleges/universities?\r\nThank you",
    "g-recaptcha-response": "2a3663e2e8b5bfd19b865b12da1482104c065be1c52c6a2fad137e06afb0cdfa",
    "timestamp": "Tue, 06 Oct 2020 13:52:37 GMT",
    "ip": "ed5045677ad26d8c58f868181b118c0e402a35ce5c2ee10642bc5fa1eb2cbfdb"
}
```
