### ISSUE TITLE
[feature request] Explainer Videos for rdfmapped.com

### ISSUE THREAD

**Issue by rdfbot** [almasen/rdf-mapped#144]
### Explainer Videos for rdfmapped.com

Hi,

We'd like to introduce to you our explainer video service which we feel can benefit your site rdfmapped.com.

Check out some of our existing videos here:
https://www.youtube.com/watch?v=zvGF7uRfH04
https://www.youtube.com/watch?v=cZPsp217Iik
https://www.youtube.com/watch?v=JHfnqS2zpU8

All of our videos are in a similar animated format as the above examples and we have voice over artists with US/UK/Australian accents.

They can show a solution to a problem or simply promote one of your products or services. They are concise, can be uploaded to video such as Youtube, and can be embedded into your website or featured on landing pages.

Our prices are as follows depending on video length:
0-1 minutes = $189
1-2 minutes = $339
2-3 minutes = $449

*All prices above are in USD and include a custom video, full script and a voice-over.

If this is something you would like to discuss further, don't hesitate to get in touch.

Kind Regards,
Steve

Metadata:
```yaml
{
    "_csrf": "44defbfc40e76fd2f50a6c306106d8e0ee3d0c2d55688e9b1324e6c147508d02",
    "reason": "feature_request",
    "name": "e5d1d88cb7cf01c5fac8442ea35ed5656bfb94e233ac4f6b25f1bb10b4ada207",
    "subject": "Explainer Videos for rdfmapped.com",
    "email": "b79d228965fd0dc971fcc0723d5e35e1f00ac82eb4b927b8e7283c11dd7c3102",
    "message": "Hi,\r\n\r\nWe'd like to introduce to you our explainer video service which we feel can benefit your site rdfmapped.com.\r\n\r\nCheck out some of our existing videos here:\r\nhttps://www.youtube.com/watch?v=zvGF7uRfH04\r\nhttps://www.youtube.com/watch?v=cZPsp217Iik\r\nhttps://www.youtube.com/watch?v=JHfnqS2zpU8\r\n\r\nAll of our videos are in a similar animated format as the above examples and we have voice over artists with US/UK/Australian accents.\r\n\r\nThey can show a solution to a problem or simply promote one of your products or services. They are concise, can be uploaded to video such as Youtube, and can be embedded into your website or featured on landing pages.\r\n\r\nOur prices are as follows depending on video length:\r\n0-1 minutes = $189\r\n1-2 minutes = $339\r\n2-3 minutes = $449\r\n\r\n*All prices above are in USD and include a custom video, full script and a voice-over.\r\n\r\nIf this is something you would like to discuss further, don't hesitate to get in touch.\r\n\r\nKind Regards,\r\nSteve",
    "g-recaptcha-response": "20d8719f8e05383e43777d8f943024896ca918efd843cf35ccddf5d57d0b29ed",
    "timestamp": "Wed, 24 Feb 2021 11:45:15 GMT",
    "ip": "f4973eeac5521c627543d5850df401cd07136afe9cc2ce8b97be8ff3ebd7fcef"
}
```
