### ISSUE TITLE
[bugreport] Instead, congrats

### ISSUE THREAD

**Issue by rdfbot** [almasen/rdf-mapped#145]
### Instead, congrats

Good day, 

My name is Eric and unlike a lot of emails you might get, I wanted to instead provide you with a word of encouragement – Congratulations

What for?  

Part of my job is to check out websites and the work you’ve done with rdfmapped.com definitely stands out. 

It’s clear you took building a website seriously and made a real investment of time and resources into making it top quality.

There is, however, a catch… more accurately, a question…

So when someone like me happens to find your site – maybe at the top of the search results (nice job BTW) or just through a random link, how do you know? 

More importantly, how do you make a connection with that person?

Studies show that 7 out of 10 visitors don’t stick around – they’re there one second and then gone with the wind.

Here’s a way to create INSTANT engagement that you may not have known about… 

Talk With Web Visitor is a software widget that’s works on your site, ready to capture any visitor’s Name, Email address and Phone Number.  It lets you know INSTANTLY that they’re interested – so that you can talk to that lead while they’re literally checking out rdfmapped.com.

CLICK HERE https://talkwithwebvisitors.com to try out a Live Demo with Talk With Web Visitor now to see exactly how it works.

It could be a game-changer for your business – and it gets even better… once you’ve captured their phone number, with our new SMS Text With Lead feature, you can automatically start a text (SMS) conversation – immediately (and there’s literally a 100X difference between contacting someone within 5 minutes versus 30 minutes.)

Plus then, even if you don’t close a deal right away, you can connect later on with text messages for new offers, content links, even just follow up notes to build a relationship.

Everything I’ve just described is simple, easy, and effective. 

CLICK HERE https://talkwithwebvisitors.com to discover what Talk With Web Visitor can do for your business.

You could be converting up to 100X more leads today!

Eric
PS: Talk With Web Visitor offers a FREE 14 days trial – and it even includes International Long Distance Calling. 
You have customers waiting to talk with you right now… don’t keep them waiting. 
CLICK HERE https://talkwithwebvisitors.com to try Talk With Web Visitor now.

If you'd like to unsubscribe click here http://talkwithwebvisitors.com/unsubscribe.aspx?d=rdfmapped.com

Metadata:
```yaml
{
    "_csrf": "531a734a28952742cd4953537667a4f1ba675c63b9f327498017fc69affc60ac",
    "reason": "bugreport",
    "name": "8d1048d8f86b0d920603bf221f69960d008baed8a2adbf45ee59b351daaec3d6",
    "subject": "Instead, congrats",
    "email": "245cc64a97525d2d01fb32c9be657bbd00487c5552e4eddfe1a111617d1a2a68",
    "message": "Good day, \r\n\r\nMy name is Eric and unlike a lot of emails you might get, I wanted to instead provide you with a word of encouragement – Congratulations\r\n\r\nWhat for?  \r\n\r\nPart of my job is to check out websites and the work you’ve done with rdfmapped.com definitely stands out. \r\n\r\nIt’s clear you took building a website seriously and made a real investment of time and resources into making it top quality.\r\n\r\nThere is, however, a catch… more accurately, a question…\r\n\r\nSo when someone like me happens to find your site – maybe at the top of the search results (nice job BTW) or just through a random link, how do you know? \r\n\r\nMore importantly, how do you make a connection with that person?\r\n\r\nStudies show that 7 out of 10 visitors don’t stick around – they’re there one second and then gone with the wind.\r\n\r\nHere’s a way to create INSTANT engagement that you may not have known about… \r\n\r\nTalk With Web Visitor is a software widget that’s works on your site, ready to capture any visitor’s Name, Email address and Phone Number.  It lets you know INSTANTLY that they’re interested – so that you can talk to that lead while they’re literally checking out rdfmapped.com.\r\n\r\nCLICK HERE https://talkwithwebvisitors.com to try out a Live Demo with Talk With Web Visitor now to see exactly how it works.\r\n\r\nIt could be a game-changer for your business – and it gets even better… once you’ve captured their phone number, with our new SMS Text With Lead feature, you can automatically start a text (SMS) conversation – immediately (and there’s literally a 100X difference between contacting someone within 5 minutes versus 30 minutes.)\r\n\r\nPlus then, even if you don’t close a deal right away, you can connect later on with text messages for new offers, content links, even just follow up notes to build a relationship.\r\n\r\nEverything I’ve just described is simple, easy, and effective. \r\n\r\nCLICK HERE https://talkwithwebvisitors.com to discover what Talk With Web Visitor can do for your business.\r\n\r\nYou could be converting up to 100X more leads today!\r\n\r\nEric\r\nPS: Talk With Web Visitor offers a FREE 14 days trial – and it even includes International Long Distance Calling. \r\nYou have customers waiting to talk with you right now… don’t keep them waiting. \r\nCLICK HERE https://talkwithwebvisitors.com to try Talk With Web Visitor now.\r\n\r\nIf you'd like to unsubscribe click here http://talkwithwebvisitors.com/unsubscribe.aspx?d=rdfmapped.com\r\n",
    "g-recaptcha-response": "4d40fb3f480cf9f4383e6a700d44879ec3a1014141285f8ebb1707bfc3b0d638",
    "timestamp": "Wed, 24 Mar 2021 21:24:54 GMT",
    "ip": "517427b162b34faa9e92f85b6f51e1b5f896aea255f1486480cea7a96ea8b2bd"
}
```
