### ISSUE TITLE
[feature request] There they go…

### ISSUE THREAD

**Issue by rdfbot** [almasen/rdf-mapped#160]
### There they go…

Hey, my name’s Eric and for just a second, imagine this…

- Someone does a search and winds up at rdfmapped.com.

- They hang out for a minute to check it out.  “I’m interested… but… maybe…”

- And then they hit the back button and check out the other search results instead. 

- Bottom line – you got an eyeball, but nothing else to show for it.

- There they go.

This isn’t really your fault – it happens a LOT – studies show 7 out of 10 visitors to any site disappear without leaving a trace.

But you CAN fix that.

Talk With Web Visitor is a software widget that’s works on your site, ready to capture any visitor’s Name, Email address and Phone Number.  It lets you know right then and there – enabling you to call that lead while they’re literally looking over your site.

CLICK HERE http://talkwithcustomer.com to try out a Live Demo with Talk With Web Visitor now to see exactly how it works.

Time is money when it comes to connecting with leads – the difference between contacting someone within 5 minutes versus 30 minutes later can be huge – like 100 times better!

Plus, now that you have their phone number, with our new SMS Text With Lead feature you can automatically start a text (SMS) conversation… so even if you don’t close a deal then, you can follow up with text messages for new offers, content links, even just “how you doing?” notes to build a relationship.

Strong stuff.

CLICK HERE http://talkwithcustomer.com to discover what Talk With Web Visitor can do for your business.

You could be converting up to 100X more leads today!

Eric
PS: Talk With Web Visitor offers a FREE 14 days trial – and it even includes International Long Distance Calling. 
You have customers waiting to talk with you right now… don’t keep them waiting. 
CLICK HERE http://talkwithcustomer.com to try Talk With Web Visitor now.

If you'd like to unsubscribe click here http://talkwithcustomer.com/unsubscribe.aspx?d=rdfmapped.com

Metadata:
```yaml
{
    "_csrf": "ca874c2f5a24a42549850ffb672b0e5c761bc4fac0ee6c0e60a467402e5abb99",
    "reason": "feature_request",
    "name": "8d1048d8f86b0d920603bf221f69960d008baed8a2adbf45ee59b351daaec3d6",
    "subject": "There they go…",
    "email": "245cc64a97525d2d01fb32c9be657bbd00487c5552e4eddfe1a111617d1a2a68",
    "message": "Hey, my name’s Eric and for just a second, imagine this…\r\n\r\n- Someone does a search and winds up at rdfmapped.com.\r\n\r\n- They hang out for a minute to check it out.  “I’m interested… but… maybe…”\r\n\r\n- And then they hit the back button and check out the other search results instead. \r\n\r\n- Bottom line – you got an eyeball, but nothing else to show for it.\r\n\r\n- There they go.\r\n\r\nThis isn’t really your fault – it happens a LOT – studies show 7 out of 10 visitors to any site disappear without leaving a trace.\r\n\r\nBut you CAN fix that.\r\n\r\nTalk With Web Visitor is a software widget that’s works on your site, ready to capture any visitor’s Name, Email address and Phone Number.  It lets you know right then and there – enabling you to call that lead while they’re literally looking over your site.\r\n\r\nCLICK HERE http://talkwithcustomer.com to try out a Live Demo with Talk With Web Visitor now to see exactly how it works.\r\n\r\nTime is money when it comes to connecting with leads – the difference between contacting someone within 5 minutes versus 30 minutes later can be huge – like 100 times better!\r\n\r\nPlus, now that you have their phone number, with our new SMS Text With Lead feature you can automatically start a text (SMS) conversation… so even if you don’t close a deal then, you can follow up with text messages for new offers, content links, even just “how you doing?” notes to build a relationship.\r\n\r\nStrong stuff.\r\n\r\nCLICK HERE http://talkwithcustomer.com to discover what Talk With Web Visitor can do for your business.\r\n\r\nYou could be converting up to 100X more leads today!\r\n\r\nEric\r\nPS: Talk With Web Visitor offers a FREE 14 days trial – and it even includes International Long Distance Calling. \r\nYou have customers waiting to talk with you right now… don’t keep them waiting. \r\nCLICK HERE http://talkwithcustomer.com to try Talk With Web Visitor now.\r\n\r\nIf you'd like to unsubscribe click here http://talkwithcustomer.com/unsubscribe.aspx?d=rdfmapped.com\r\n",
    "g-recaptcha-response": "3c35b2374db029b4b99e869cb1a9a9d084d5df3ad9ee5d6ffeb1c93847683062",
    "timestamp": "Sun, 27 Jun 2021 14:16:54 GMT",
    "ip": "8810272851255342257be5f790d1d701380b370f099b7e736ff8e79ec5ec408a"
}
```
