### ISSUE TITLE
[bugreport] Auto bugreport for route /course/4

### ISSUE THREAD

**Issue by almasen** [almasen/rdf-mapped#41]
```yaml
{
    "timestamp": "Thu, 20 Aug 2020 22:02:59 GMT",
    "originalUrl": "/course/4",
    "ip": "4240b57667d8195056fee465cd20cbeb5502ececf3f0aaa13bf863ac6e1befd1",
    "email": "6e170de96074eac676727c7f7ac630f7f37fd5be12fa3fe088de3174ead54f03",
    "report": "TEST8: Testing new formatting"
}
```
