### ISSUE TITLE
[bugreport] Auto bugreport for route /course/4

### ISSUE THREAD

**Issue by almasen** [almasen/rdf-mapped#42]
```yaml
{
    "timestamp": "Thu, 20 Aug 2020 22:11:29 GMT",
    "originalUrl": "/course/4",
    "ip": "4240b57667d8195056fee465cd20cbeb5502ececf3f0aaa13bf863ac6e1befd1",
    "email": "bb0d035db15e62b31bac3bb0dbe9769b7b0d6a966c60bf735a4efabe25ec4e65",
    "report": "TEST9"
}
```
