### ISSUE TITLE
[feature request] undefined

### ISSUE THREAD

**Issue by almasen** [almasen/rdf-mapped#43]
```yaml
{
    "name": "822701a0a3d4c79073fd2ac36f028a1ea2126445244454741545f954c70b8255",
    "subject": "Test Subject",
    "email": "6e170de96074eac676727c7f7ac630f7f37fd5be12fa3fe088de3174ead54f03",
    "message": "Test5: Feature request",
    "g-recaptcha-response": "03AGdBq27Al-uGGUjWQ_uRHXpClZCJJtRDYwdoxBypbVZe9EmjCCfbQ1mP-E4bBOPHYBmlr7F3tJ1n7az83vFaMpkY8lKH-Td067MgbpmiftR2fIg1PbvaVhYtk69h8ZM_4c52624oizhJzIfe0T4WuHkYnO7Br5ekMoT6vnlpAyA2Vt5g3xz_ndi3_4HtJBGQcJpvvSzhpjXJbqxXojxPFrBYlqNFKmsnrBn98rYce-VpD3MA6iWh9HyF8_S_4zE_X2vlukHW2I2axkhpl4745Us1DO-tJkePVJPdT45T9atu1R55AmO5n5kAL3l1Jc2ngAmvjOEV6kOukiMpDrae9k5L-VsVOH1Zb77VbbFu_v-MMQ3V4jQSCsTUlN2sN5XHJQEq0cCZ7F0S",
    "timestamp": "Thu, 20 Aug 2020 22:20:43 GMT",
    "ip": "4240b57667d8195056fee465cd20cbeb5502ececf3f0aaa13bf863ac6e1befd1"
}
```
