### ISSUE TITLE
[feature request] Test Subject

### ISSUE THREAD

**Issue by almasen** [almasen/rdf-mapped#44]
```yaml
{
    "reason": "feature_request",
    "name": "822701a0a3d4c79073fd2ac36f028a1ea2126445244454741545f954c70b8255",
    "subject": "Test Subject",
    "email": "8d557821ae005444adffc7d90b753dc8cc5be0f87635657d3312c9f0f32511ec",
    "message": "Test8: Testing from trigger",
    "g-recaptcha-response": "822701a0a3d4c79073fd2ac36f028a1ea2126445244454741545f954c70b8255",
    "timestamp": "Thu, 20 Aug 2020 23:32:05 GMT",
    "ip": "4240b57667d8195056fee465cd20cbeb5502ececf3f0aaa13bf863ac6e1befd1"
}
```
