### ISSUE TITLE
[bugreport] Auto bugreport for route undefined

### ISSUE THREAD

**Issue by almasen** [almasen/rdf-mapped#45]
```yaml
{
    "reason": "bugreport",
    "name": "95c80ff5d5862f3dc2709f09f2665cfa3f0bbd039bcc37ec05a8fb929520b2b8",
    "subject": "Test Subject 3",
    "email": "6e170de96074eac676727c7f7ac630f7f37fd5be12fa3fe088de3174ead54f03",
    "message": "Test 9: Form trigger",
    "g-recaptcha-response": "e3ad0bfaf3103ba1320683459fc529470528ea721f52b1658f0ac0d4677fb245",
    "timestamp": "Thu, 20 Aug 2020 23:34:26 GMT",
    "ip": "4240b57667d8195056fee465cd20cbeb5502ececf3f0aaa13bf863ac6e1befd1"
}
```
