### ISSUE TITLE
[feature request] Test Subject 3

### ISSUE THREAD

**Issue by almasen** [almasen/rdf-mapped#46]
```yaml
{
    "reason": "feature_request",
    "name": "95c80ff5d5862f3dc2709f09f2665cfa3f0bbd039bcc37ec05a8fb929520b2b8",
    "subject": "Test Subject 3",
    "email": "8d557821ae005444adffc7d90b753dc8cc5be0f87635657d3312c9f0f32511ec",
    "message": "Test10: Feature req. from form",
    "g-recaptcha-response": "416e70fee25d0c3a4a2008a1c209f50fb69ade7b7e436820d14cb964a8e546eb",
    "timestamp": "Thu, 20 Aug 2020 23:35:44 GMT",
    "ip": "4240b57667d8195056fee465cd20cbeb5502ececf3f0aaa13bf863ac6e1befd1"
}
```
