### ISSUE TITLE
[feature request] Testing new issue format

### ISSUE THREAD

**Issue by almasen** [almasen/rdf-mapped#48]
### Testing new issue format

Testing new issue format

Metadata:
```yaml
{
    "reason": "feature_request",
    "name": "43c8f3fc7e0b3045d48e38c3846ddddeac5b1e2c29d88d1c0009c2c1cbdf2e96",
    "subject": "Testing new issue format",
    "email": "e3064b969b7ebf26d30f88a49b7b64d6a934d4064cce0761f084a6f9b8a19a87",
    "message": "Testing new issue format, this is the detailed message blah blah",
    "g-recaptcha-response": "6c6ce0bf783cb58a5dcda1c73d527c54be2b1cddfd1709729e8c97f51a517421",
    "timestamp": "Thu, 20 Aug 2020 23:45:25 GMT",
    "ip": "4240b57667d8195056fee465cd20cbeb5502ececf3f0aaa13bf863ac6e1befd1"
}
```
