### ISSUE TITLE
[bugreport] Testing new issue format2

### ISSUE THREAD

**Issue by almasen** [almasen/rdf-mapped#49]
### Testing new issue format2

Testing new issue format, this is the detailed message about technical issue blah balh

Metadata:
```yaml
{
    "reason": "bugreport",
    "name": "43cdc9c47ac951e97f5f5b211a25d82401f5e7d1435020e5b9afa3d190c3e30f",
    "subject": "Testing new issue format2",
    "email": "4d3f8cb0fa7a1ebdca5fb47786f47fd162bdd3a3223a7088f37da93817473530",
    "message": "Testing new issue format, this is the detailed message about technical issue blah balh",
    "g-recaptcha-response": "1eedb508d15e59a0a7e128f2ff80c974ee6540e8395378f0a6821c6dd4b5abe0",
    "timestamp": "Thu, 20 Aug 2020 23:47:19 GMT",
    "ip": "4240b57667d8195056fee465cd20cbeb5502ececf3f0aaa13bf863ac6e1befd1"
}
```
