### ISSUE TITLE
[bugreport] Auto bugreport for route /course/2

### ISSUE THREAD

**Issue by almasen** [almasen/rdf-mapped#50]
### Route /course/2

Testing new issue format from course page, let's see

Metadata:
```yaml
{
    "timestamp": "Thu, 20 Aug 2020 23:48:08 GMT",
    "originalUrl": "/course/2",
    "ip": "4240b57667d8195056fee465cd20cbeb5502ececf3f0aaa13bf863ac6e1befd1",
    "email": "6f57974dda524735f079ee9c47b3ed206703a5ee0f51011c5ea65f7981a41418",
    "report": "Testing new issue format from course page, let's see"
}
```
