### ISSUE TITLE
[bugreport] Auto bugreport for route /course/4

### ISSUE THREAD

**Issue by almasen** [almasen/rdf-mapped#52]
### Route /course/4

Test15

Metadata:
```yaml
{
    "timestamp": "Thu, 20 Aug 2020 23:57:08 GMT",
    "originalUrl": "/course/4",
    "ip": "4240b57667d8195056fee465cd20cbeb5502ececf3f0aaa13bf863ac6e1befd1",
    "email": "",
    "report": "Test15"
}
```
