### ISSUE TITLE
[bugreport] Auto bugreport for route /course/5

### ISSUE THREAD

**Issue by almasen** [almasen/rdf-mapped#53]
### Route /course/5

asdf

Metadata:
```yaml
{
    "timestamp": "Thu, 20 Aug 2020 23:57:55 GMT",
    "originalUrl": "/course/5",
    "ip": "4240b57667d8195056fee465cd20cbeb5502ececf3f0aaa13bf863ac6e1befd1",
    "email": "",
    "report": "asdf"
}
```
