### ISSUE TITLE
[bugreport] Auto bugreport for route /course/5

### ISSUE THREAD

**Issue by almasen** [almasen/rdf-mapped#59]
### Route /course/5

TEST18: Bugrep from route

Metadata:
```yaml
{
    "timestamp": "Sat, 22 Aug 2020 23:29:38 GMT",
    "originalUrl": "/course/5",
    "ip": "4240b57667d8195056fee465cd20cbeb5502ececf3f0aaa13bf863ac6e1befd1",
    "email": "1e22dec3409c2d9e123addde57842903a23be8f122a1fe845e06ce8f441fe589",
    "report": "TEST18: Bugrep from route"
}
```
