### ISSUE TITLE
[bugreport] Auto bugreport for route /course/503

### ISSUE THREAD

**Issue by rdfbot** [almasen/rdf-mapped#76]
### Route /course/503

Testing automatic issue creation #28

Metadata:
```yaml
{
    "timestamp": "Mon, 14 Sep 2020 07:18:13 GMT",
    "originalUrl": "/course/503",
    "ip": "f733a7969de244ab799be43d0c6aed066807330276281136416d850bc60fc965",
    "email": "",
    "report": "Testing automatic issue creation #28"
}
```
