### ISSUE TITLE
[feature request] Testing automatic issue creation #29

### ISSUE THREAD

**Issue by rdfbot** [almasen/rdf-mapped#77]
### Testing automatic issue creation #29

Testing automatic issue creation #28
feature request sample

Metadata:
```yaml
{
    "reason": "feature_request",
    "name": "438817a8e18bf7088efbd8eee99782494f9965f9dd46261aeabcd71655cb4929",
    "subject": "Testing automatic issue creation #29",
    "email": "a1a59f2d498bf1680a25abb8f1506a1e0841d4131966768d4bfba80a18812bff",
    "message": "Testing automatic issue creation #28\r\nfeature request sample",
    "g-recaptcha-response": "bf9d2557dd473adb86d156a5792e95b9435deeb7742a100b2c6b7f1938cc71f4",
    "timestamp": "Mon, 14 Sep 2020 07:19:57 GMT",
    "ip": "f733a7969de244ab799be43d0c6aed066807330276281136416d850bc60fc965"
}
```
