### ISSUE TITLE
[bugreport] Auto bugreport for route undefined

### ISSUE THREAD

**Issue by rdfbot** [almasen/rdf-mapped#88]
### Route undefined

Something is wrong

Metadata:
```yaml
{
    "report": "Something is wrong",
    "originalURL": "/course/1"
}
```
