### ISSUE TITLE
[feature request] Complaint!

### ISSUE THREAD

**Issue by rdfbot** [almasen/rdf-mapped#89]
### Complaint!

Why can't this site brew my tea?

Metadata:
```yaml
{
    "message": "Why can't this site brew my tea?",
    "subject": "Complaint!"
}
```
