### ISSUE TITLE
[bugreport] Auto bugreport for route undefined

### ISSUE THREAD

**Issue by rdfbot** [almasen/rdf-mapped#90]
### Route undefined

TESTING RDFBOT-0

Metadata:
```yaml
{
    "report": "TESTING RDFBOT-0",
    "originalURL": "rdfbot-testing-bugrep-0"
}
```
