### ISSUE TITLE
[feature request] rdfbot-testing-fr-0

### ISSUE THREAD

**Issue by rdfbot** [almasen/rdf-mapped#91]
### rdfbot-testing-fr-0

Why can't this site brew my tea?-0

Metadata:
```yaml
{
    "message": "Why can't this site brew my tea?-0",
    "subject": "rdfbot-testing-fr-0"
}
```
