### ISSUE TITLE
[bugreport] Auto bugreport for route undefined

### ISSUE THREAD

**Issue by rdfbot** [almasen/rdf-mapped#92]
### Route undefined

TESTING RDFBOT-1

Metadata:
```yaml
{
    "report": "TESTING RDFBOT-1",
    "originalURL": "rdfbot-testing-bugrep-1"
}
```
