### ISSUE TITLE
[feature request] rdfbot-testing-fr-1

### ISSUE THREAD

**Issue by rdfbot** [almasen/rdf-mapped#93]
### rdfbot-testing-fr-1

Why can't this site brew my tea?-1

Metadata:
```yaml
{
    "message": "Why can't this site brew my tea?-1",
    "subject": "rdfbot-testing-fr-1"
}
```
