### ISSUE TITLE
[bugreport] Auto bugreport for route undefined

### ISSUE THREAD

**Issue by rdfbot** [almasen/rdf-mapped#94]
### Route undefined

TESTING RDFBOT-2

Metadata:
```yaml
{
    "report": "TESTING RDFBOT-2",
    "originalURL": "rdfbot-testing-bugrep-2"
}
```
