### ISSUE TITLE
[feature request] rdfbot-testing-fr-2

### ISSUE THREAD

**Issue by rdfbot** [almasen/rdf-mapped#95]
### rdfbot-testing-fr-2

Why can't this site brew my tea?-2

Metadata:
```yaml
{
    "message": "Why can't this site brew my tea?-2",
    "subject": "rdfbot-testing-fr-2"
}
```
