### ISSUE TITLE
[bugreport] Auto bugreport for route undefined

### ISSUE THREAD

**Issue by rdfbot** [almasen/rdf-mapped#96]
### Route undefined

TESTING RDFBOT-3

Metadata:
```yaml
{
    "report": "TESTING RDFBOT-3",
    "originalURL": "rdfbot-testing-bugrep-3"
}
```
