### ISSUE TITLE
[feature request] rdfbot-testing-fr-3

### ISSUE THREAD

**Issue by rdfbot** [almasen/rdf-mapped#97]
### rdfbot-testing-fr-3

Why can't this site brew my tea?-3

Metadata:
```yaml
{
    "message": "Why can't this site brew my tea?-3",
    "subject": "rdfbot-testing-fr-3"
}
```
