### ISSUE TITLE
[bugreport] Auto bugreport for route undefined

### ISSUE THREAD

**Issue by rdfbot** [almasen/rdf-mapped#98]
### Route undefined

TESTING RDFBOT-4

Metadata:
```yaml
{
    "report": "TESTING RDFBOT-4",
    "originalURL": "rdfbot-testing-bugrep-4"
}
```
