### ISSUE TITLE
[feature request] rdfbot-testing-fr-4

### ISSUE THREAD

**Issue by rdfbot** [almasen/rdf-mapped#99]
### rdfbot-testing-fr-4

Why can't this site brew my tea?-4

Metadata:
```yaml
{
    "message": "Why can't this site brew my tea?-4",
    "subject": "rdfbot-testing-fr-4"
}
```
